//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DU_AN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPro()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int IDOrder { get; set; }
        public Nullable<int> IDCus { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public string NameProduct { get; set; }
        public Nullable<int> QuantityProduct { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> Deliveryfee { get; set; }
        public Nullable<double> TotalPay { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
