//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DU_AN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int IDOrder { get; set; }
        public int IDProduct { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<int> IDCus { get; set; }
        public string AddressCus { get; set; }
        public Nullable<double> TotalPay { get; set; }
        public string InforBill { get; set; }
        public string DeliveryInfor { get; set; }
    
        public virtual OrderPro OrderPro { get; set; }
        public virtual Product Product { get; set; }
    }
}
