//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DU_AN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            imageProduct1 = "~/Content/img/add.png";
        }
    
        public int ID { get; set; }
        public int IDProduct { get; set; }
        public string NameProduct { get; set; }
        public string Trademark { get; set; }
        public Nullable<int> QuantityProduct { get; set; }
        public Nullable<double> PriceProduct { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Feedback { get; set; }
        public string DescriptionProduct { get; set; }
        public string imageProduct1 { get; set; }
        public string imageProduct2 { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
